"""Add meta to file

Revision ID: ab5b51940dfc
Revises: 9a91325da470
Create Date: 2021-09-16 21:34:08.756075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab5b51940dfc"
down_revision = "9a91325da470"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("meta", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "meta")
    # ### end Alembic commands ###
