"""add jpeg extension

Revision ID: bcfcc16e8158
Revises: 8a6d691f3a36
Create Date: 2021-09-20 15:33:58.199356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfcc16e8158'
down_revision = '8a6d691f3a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('extension', sa.Enum('mp4', 'jpg', 'png', 'jpeg', name='allowedextensions'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'extension')
    # ### end Alembic commands ###
