"""change blob

Revision ID: d268d699fb9d
Revises: 5ee31c27d8ad
Create Date: 2021-09-16 01:35:16.212551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d268d699fb9d"
down_revision = "5ee31c27d8ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "data")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("data", sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
